# Generated by Django 3.0.6 on 2020-06-22 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    TaskStatus = apps.get_model("tasks", "TaskStatus")
    db_alias = schema_editor.connection.alias
    TaskStatus.objects.using(db_alias).bulk_create(
        [
            TaskStatus(name="новый"),
            TaskStatus(name="в работе"),
            TaskStatus(name="на тестировании"),
            TaskStatus(name="завершен"),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0003_auto_20200511_1844"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.RunPython(forwards_func),

        migrations.AlterModelOptions(name="tag", options={"ordering": ["name"]},),
        migrations.RenameField(model_name="task", old_name="title", new_name="name",),
        migrations.RemoveField(model_name="task", name="assigner",),
        migrations.RemoveField(model_name="task", name="canceled_at",),
        migrations.RemoveField(model_name="task", name="state",),
        migrations.RemoveField(model_name="task", name="updated_at",),
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="tasks.TaskStatus",
            ),
        ),
    ]
